version: '3'

volumes:
  standalone_data:

services:
  node:
    build: ./
    container_name: server-ialift_api
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./.env
    command: npm start
    network_mode: bridge
