FROM eu.gcr.io/talento-corporativo-gcp/ruby18:latest
MAINTAINER Iñaki Quesada <i.quesada@talentocorporativo.com>

ENV HOME /root

# GEMS
#ADD ./files/installgems.sh /tmp
#RUN bash /tmp/installgems.sh

# Binary
#ADD ./binary/wkhtmltopdf /usr/local/bin

# EXPOSE
EXPOSE 80

