version: '3'

volumes:
  standalone_data:

services:
  mongodb_latest:
    container_name: mongodb_latest
    hostname: mongodb_latest
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - standalone_data:/data/db
    ports:
        - 27017:27017
